name: gptintent
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - joblib=1.5.3
  - khronos-opencl-icd-loader=2024.10.24
  - libblas=3.11.0
  - libboost=1.88.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libexpat=2.7.4
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.11.0
  - liblightgbm=4.6.0
  - liblzma=5.8.2
  - libopenblas=0.3.30
  - libsqlite=3.51.2
  - libxgboost=3.2.0
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvm-openmp=21.1.8
  - ncurses=6.5
  - numpy=2.4.2
  - opencl-headers=2025.06.13
  - openssl=3.6.1
  - packaging=26.0
  - pandas=3.0.1
  - pip=26.0.1
  - py-xgboost=3.2.0
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pyyaml=6.0.3
  - readline=8.3
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - setuptools=82.0.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.46.3
  - xgboost=3.2.0
  - yaml=0.2.5
  - zstd=1.5.7
  - pip:
      - filelock==3.24.3
      - fsspec==2026.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6.1
      - sympy==1.14.0
      - torch==2.2.2
      - typing-extensions==4.15.0
prefix: /Users/alexandrakim/opt/anaconda3/envs/gptintent
